FROM  osixia/openldap:1.3.0

ENV LDAP_LOG_LEVEL "256"
ENV LDAP_ORGANISATION "LIFERAY"
ENV LDAP_DOMAIN "liferay.nowhere.com"
ENV LDAP_ADMIN_PASSWORD "demo"
ENV LDAP_TLS_ENFORCE false

# extending schema example
#ADD extra.schema /container/service/slapd/assets/config/bootstrap/schema/extra.schema

